name: Check Secrets availability

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Read a Variable
      run: echo "MongoDB URI is ${{ vars.MONGODB_URI }}" 
